import type { DialogueLineDefinition, DialogueSequenceDefinition } from './types'

export const G01_SCENE_00_DIALOGUES: DialogueLineDefinition[] = [
  {
    dialogueId: 'DLG-G01-00-001',
    sequenceId: 'SEQ-G01-00-OPENING',
    sceneId: 'SCN-G01-00',
    sequence: 1,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'alert',
    side: 'left',
    text: '七码？回答。',
    blocking: true,
    skippable: false,
    effects: [
      { type: 'unlock-profile', characterId: 'xingyu' },
      { type: 'set-character-state', characterId: 'xingyu', portraitState: 'alert' },
    ],
    nextDialogueId: 'DLG-G01-00-002',
  },
  {
    dialogueId: 'DLG-G01-00-002',
    sequenceId: 'SEQ-G01-00-OPENING',
    sceneId: 'SCN-G01-00',
    sequence: 2,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'nervous',
    side: 'left',
    text: '七码，导航核心听得到吗？',
    blocking: true,
    skippable: false,
    effects: [{ type: 'set-character-state', characterId: 'xingyu', portraitState: 'nervous' }],
    nextDialogueId: 'DLG-G01-00-003',
  },
  {
    dialogueId: 'DLG-G01-00-003',
    sequenceId: 'SEQ-G01-00-OPENING',
    sceneId: 'SCN-G01-00',
    sequence: 3,
    speakerId: 'system',
    speakerName: '拾光号系统',
    portraitState: 'warning',
    side: 'right',
    text: '主电网断开。导航核心离线。维修舱进入应急照明模式。',
    blocking: true,
    skippable: false,
    effects: [],
    nextDialogueId: 'DLG-G01-00-004',
  },
  {
    dialogueId: 'DLG-G01-00-004',
    sequenceId: 'SEQ-G01-00-OPENING',
    sceneId: 'SCN-G01-00',
    sequence: 4,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'determined',
    side: 'left',
    text: '没有回应。先找光，再找故障。',
    blocking: true,
    skippable: false,
    effects: [{ type: 'set-character-state', characterId: 'xingyu', portraitState: 'determined' }],
  },
  {
    dialogueId: 'DLG-G01-00-005',
    sequenceId: 'SEQ-G01-00-HANDLAMP',
    sceneId: 'SCN-G01-00',
    sequence: 1,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'thinking',
    side: 'left',
    text: '手灯还能亮。配电盒在中央控制台左侧。',
    blocking: true,
    skippable: true,
    effects: [{ type: 'set-character-state', characterId: 'xingyu', portraitState: 'thinking' }],
  },
  {
    dialogueId: 'DLG-G01-00-006',
    sequenceId: 'SEQ-G01-00-CABINET',
    sceneId: 'SCN-G01-00',
    sequence: 1,
    speakerId: 'system',
    speakerName: '拾光号系统',
    portraitState: 'warning',
    side: 'right',
    text: '熔断点确认。维修柜机械锁已解除。',
    blocking: true,
    skippable: true,
    effects: [],
    nextDialogueId: 'DLG-G01-00-007',
  },
  {
    dialogueId: 'DLG-G01-00-007',
    sequenceId: 'SEQ-G01-00-CABINET',
    sceneId: 'SCN-G01-00',
    sequence: 2,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'normal',
    side: 'left',
    text: '找一枚完整保险丝。烧黑的那枚别再碰。',
    blocking: true,
    skippable: true,
    effects: [{ type: 'set-character-state', characterId: 'xingyu', portraitState: 'normal' }],
  },
  {
    dialogueId: 'DLG-G01-00-008',
    sequenceId: 'SEQ-G01-00-FUSE-FOUND',
    sceneId: 'SCN-G01-00',
    sequence: 1,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'thinking',
    side: 'left',
    text: '临时保险丝规格一致。接入应急照明槽。',
    blocking: true,
    skippable: true,
    effects: [{ type: 'set-character-state', characterId: 'xingyu', portraitState: 'thinking' }],
  },
  {
    dialogueId: 'DLG-G01-00-009',
    sequenceId: 'SEQ-G01-00-SWITCH',
    sceneId: 'SCN-G01-00',
    sequence: 1,
    speakerId: 'system',
    speakerName: '拾光号系统',
    portraitState: 'warning',
    side: 'right',
    text: '照明回路待闭合。',
    blocking: true,
    skippable: true,
    effects: [],
    nextDialogueId: 'DLG-G01-00-010',
  },
  {
    dialogueId: 'DLG-G01-00-010',
    sequenceId: 'SEQ-G01-00-SWITCH',
    sceneId: 'SCN-G01-00',
    sequence: 2,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'determined',
    side: 'left',
    text: '保护开关还在。合闸。',
    blocking: true,
    skippable: true,
    effects: [{ type: 'set-character-state', characterId: 'xingyu', portraitState: 'determined' }],
  },
  {
    dialogueId: 'DLG-G01-00-011',
    sequenceId: 'SEQ-G01-00-LIGHTS',
    sceneId: 'SCN-G01-00',
    sequence: 1,
    speakerId: 'system',
    speakerName: '拾光号系统',
    portraitState: 'normal',
    side: 'right',
    text: '维修舱应急照明恢复。导航核心仍离线。',
    blocking: true,
    skippable: true,
    effects: [],
    nextDialogueId: 'DLG-G01-00-012',
  },
  {
    dialogueId: 'DLG-G01-00-012',
    sequenceId: 'SEQ-G01-00-LIGHTS',
    sceneId: 'SCN-G01-00',
    sequence: 2,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'alert',
    side: 'left',
    text: '七码还是没有回应。信号在船尾——去导航核心舱。',
    blocking: true,
    skippable: true,
    effects: [
      { type: 'set-character-state', characterId: 'xingyu', portraitState: 'alert' },
      { type: 'set-flag', key: 'g01_scene_00_story_complete', value: true },
    ],
  },
]
export const G01_SCENE_00_SEQUENCES: DialogueSequenceDefinition[] = [
  {
    sequenceId: 'SEQ-G01-00-OPENING',
    sceneId: 'SCN-G01-00',
    trigger: 'scene:begin',
    dialogueIds: [
      'DLG-G01-00-001',
      'DLG-G01-00-002',
      'DLG-G01-00-003',
      'DLG-G01-00-004',
    ],
    requiredFirstPlay: true,
  },
  {
    sequenceId: 'SEQ-G01-00-HANDLAMP',
    sceneId: 'SCN-G01-00',
    trigger: 'state:S1',
    dialogueIds: ['DLG-G01-00-005'],
    requiredFirstPlay: false,
  },
  {
    sequenceId: 'SEQ-G01-00-CABINET',
    sceneId: 'SCN-G01-00',
    trigger: 'state:S2',
    dialogueIds: ['DLG-G01-00-006', 'DLG-G01-00-007'],
    requiredFirstPlay: false,
  },
  {
    sequenceId: 'SEQ-G01-00-FUSE-FOUND',
    sceneId: 'SCN-G01-00',
    trigger: 'state:S3',
    dialogueIds: ['DLG-G01-00-008'],
    requiredFirstPlay: false,
  },
  {
    sequenceId: 'SEQ-G01-00-SWITCH',
    sceneId: 'SCN-G01-00',
    trigger: 'state:S4',
    dialogueIds: ['DLG-G01-00-009', 'DLG-G01-00-010'],
    requiredFirstPlay: false,
  },
  {
    sequenceId: 'SEQ-G01-00-LIGHTS',
    sceneId: 'SCN-G01-00',
    trigger: 'state:S5',
    dialogueIds: ['DLG-G01-00-011', 'DLG-G01-00-012'],
    requiredFirstPlay: false,
  },
]
