import type { DialogueLineDefinition, DialogueSequenceDefinition } from './types'

export const G01_SCENE_01_DIALOGUES: DialogueLineDefinition[] = [
  {
    dialogueId: 'DLG-G01-01-001',
    sequenceId: 'SEQ-G01-01-OPENING',
    sceneId: 'SCN-G01-01',
    sequence: 1,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'alert',
    side: 'left',
    text: '回波从这里传来。七码？',
    blocking: true,
    skippable: false,
    effects: [{ type: 'set-character-state', characterId: 'qima', portraitState: 'offline' }],
    nextDialogueId: 'DLG-G01-01-002',
  },
  {
    dialogueId: 'DLG-G01-01-002',
    sequenceId: 'SEQ-G01-01-OPENING',
    sceneId: 'SCN-G01-01',
    sequence: 2,
    speakerId: 'system',
    speakerName: '拾光号系统',
    portraitState: 'warning',
    side: 'right',
    text: '检测到教育单元离线。核心舱供电不稳定。',
    blocking: true,
    skippable: false,
    effects: [],
    nextDialogueId: 'DLG-G01-01-003',
  },
  {
    dialogueId: 'DLG-G01-01-003',
    sequenceId: 'SEQ-G01-01-OPENING',
    sceneId: 'SCN-G01-01',
    sequence: 3,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'nervous',
    side: 'left',
    text: '找到你了。外壳受损，核心还在。',
    blocking: true,
    skippable: false,
    effects: [{ type: 'set-character-state', characterId: 'xingyu', portraitState: 'nervous' }],
  },
  {
    dialogueId: 'DLG-G01-01-004',
    sequenceId: 'SEQ-G01-01-CORE',
    sceneId: 'SCN-G01-01',
    sequence: 1,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'thinking',
    side: 'left',
    text: '接口积碳，芯片和接线都松了。先找齐修复件。',
    blocking: true,
    skippable: true,
    effects: [
      { type: 'set-character-state', characterId: 'xingyu', portraitState: 'thinking' },
      { type: 'set-character-state', characterId: 'qima', portraitState: 'damaged' },
    ],
  },
  {
    dialogueId: 'DLG-G01-01-005',
    sequenceId: 'SEQ-G01-01-PARTS',
    sceneId: 'SCN-G01-01',
    sequence: 1,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'determined',
    side: 'left',
    text: '清洁刷、芯片、接线片、微型保险丝，都齐了。',
    blocking: true,
    skippable: true,
    effects: [{ type: 'set-character-state', characterId: 'xingyu', portraitState: 'determined' }],
  },
  {
    dialogueId: 'DLG-G01-01-006',
    sequenceId: 'SEQ-G01-01-CLEANED',
    sceneId: 'SCN-G01-01',
    sequence: 1,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'normal',
    side: 'left',
    text: '接口干净了。装回核心芯片。',
    blocking: true,
    skippable: true,
    effects: [{ type: 'set-character-state', characterId: 'xingyu', portraitState: 'normal' }],
  },
  {
    dialogueId: 'DLG-G01-01-007',
    sequenceId: 'SEQ-G01-01-CHIP',
    sceneId: 'SCN-G01-01',
    sequence: 1,
    speakerId: 'system',
    speakerName: '拾光号系统',
    portraitState: 'normal',
    side: 'right',
    text: '核心识别通过。等待接线片。',
    blocking: true,
    skippable: true,
    effects: [],
  },
  {
    dialogueId: 'DLG-G01-01-008',
    sequenceId: 'SEQ-G01-01-WIRING',
    sceneId: 'SCN-G01-01',
    sequence: 1,
    speakerId: 'system',
    speakerName: '拾光号系统',
    portraitState: 'warning',
    side: 'right',
    text: '线路连通。安装微型保险丝后可进入启动校准。',
    blocking: true,
    skippable: true,
    effects: [],
  },
  {
    dialogueId: 'DLG-G01-01-009',
    sequenceId: 'SEQ-G01-01-BOOT-READY',
    sceneId: 'SCN-G01-01',
    sequence: 1,
    speakerId: 'system',
    speakerName: '拾光号系统',
    portraitState: 'warning',
    side: 'right',
    text: 'EDU-0077，启动序列开始。请完成线路校准。',
    blocking: true,
    skippable: false,
    effects: [{ type: 'set-character-state', characterId: 'qima', portraitState: 'booting' }],
  },
  {
    dialogueId: 'DLG-G01-01-010',
    sequenceId: 'SEQ-G01-01-RECOVERY',
    sceneId: 'SCN-G01-01',
    sequence: 1,
    speakerId: 'system',
    speakerName: '拾光号系统',
    portraitState: 'normal',
    side: 'right',
    text: '线路校准完成。EDU-0077恢复运行。',
    blocking: true,
    skippable: false,
    effects: [
      { type: 'set-flag', key: 'qima_recovered', value: true },
      { type: 'set-character-state', characterId: 'qima', portraitState: 'normal' },
      { type: 'unlock-profile', characterId: 'qima' },
    ],
  },
  {
    dialogueId: 'DLG-G01-01-011',
    sequenceId: 'SEQ-G01-01-FIRST-CONVERSATION',
    sceneId: 'SCN-G01-01',
    sequence: 1,
    speakerId: 'qima',
    speakerName: '七码',
    portraitState: 'normal',
    side: 'right',
    text: '启动完成。我离线了四分十二秒。你没有拆船吧？',
    blocking: true,
    skippable: false,
    condition: { flag: 'qima_recovered', equals: true },
    effects: [],
    nextDialogueId: 'DLG-G01-01-012',
  },
  {
    dialogueId: 'DLG-G01-01-012',
    sequenceId: 'SEQ-G01-01-FIRST-CONVERSATION',
    sceneId: 'SCN-G01-01',
    sequence: 2,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'normal',
    side: 'left',
    text: '只拆了保险丝。',
    blocking: true,
    skippable: false,
    condition: { flag: 'qima_recovered', equals: true },
    effects: [],
    nextDialogueId: 'DLG-G01-01-013',
  },
  {
    dialogueId: 'DLG-G01-01-013',
    sequenceId: 'SEQ-G01-01-FIRST-CONVERSATION',
    sceneId: 'SCN-G01-01',
    sequence: 3,
    speakerId: 'qima',
    speakerName: '七码',
    portraitState: 'proud',
    side: 'right',
    text: '那是船的一部分。记录：回答为“拆了”。',
    blocking: true,
    skippable: false,
    condition: { flag: 'qima_recovered', equals: true },
    effects: [{ type: 'set-character-state', characterId: 'qima', portraitState: 'proud' }],
    nextDialogueId: 'DLG-G01-01-014',
  },
  {
    dialogueId: 'DLG-G01-01-014',
    sequenceId: 'SEQ-G01-01-FIRST-CONVERSATION',
    sceneId: 'SCN-G01-01',
    sequence: 4,
    speakerId: 'xingyu',
    speakerName: '星宇',
    portraitState: 'thinking',
    side: 'left',
    text: '记录完了吗？任务台刚亮。',
    blocking: true,
    skippable: false,
    condition: { flag: 'qima_recovered', equals: true },
    effects: [],
    nextDialogueId: 'DLG-G01-01-015',
  },
  {
    dialogueId: 'DLG-G01-01-015',
    sequenceId: 'SEQ-G01-01-FIRST-CONVERSATION',
    sceneId: 'SCN-G01-01',
    sequence: 5,
    speakerId: 'qima',
    speakerName: '七码',
    portraitState: 'scanning',
    side: 'right',
    text: '第一张任务单正在生成。建议：这次先读，再拆。',
    blocking: true,
    skippable: false,
    condition: { flag: 'qima_recovered', equals: true },
    effects: [
      { type: 'set-character-state', characterId: 'qima', portraitState: 'normal' },
      { type: 'set-flag', key: 'g01_scene_01_complete', value: true },
    ],
  },
]

export const G01_SCENE_01_SEQUENCES: DialogueSequenceDefinition[] = [
  {
    sequenceId: 'SEQ-G01-01-OPENING',
    sceneId: 'SCN-G01-01',
    trigger: 'scene:begin',
    dialogueIds: ['DLG-G01-01-001', 'DLG-G01-01-002', 'DLG-G01-01-003'],
    requiredFirstPlay: true,
  },
  {
    sequenceId: 'SEQ-G01-01-CORE',
    sceneId: 'SCN-G01-01',
    trigger: 'state:S1',
    dialogueIds: ['DLG-G01-01-004'],
    requiredFirstPlay: false,
  },
  {
    sequenceId: 'SEQ-G01-01-PARTS',
    sceneId: 'SCN-G01-01',
    trigger: 'state:S2',
    dialogueIds: ['DLG-G01-01-005'],
    requiredFirstPlay: false,
  },
  {
    sequenceId: 'SEQ-G01-01-CLEANED',
    sceneId: 'SCN-G01-01',
    trigger: 'state:S3',
    dialogueIds: ['DLG-G01-01-006'],
    requiredFirstPlay: false,
  },
  {
    sequenceId: 'SEQ-G01-01-CHIP',
    sceneId: 'SCN-G01-01',
    trigger: 'state:S4',
    dialogueIds: ['DLG-G01-01-007'],
    requiredFirstPlay: false,
  },
  {
    sequenceId: 'SEQ-G01-01-WIRING',
    sceneId: 'SCN-G01-01',
    trigger: 'state:S5',
    dialogueIds: ['DLG-G01-01-008'],
    requiredFirstPlay: false,
  },
  {
    sequenceId: 'SEQ-G01-01-BOOT-READY',
    sceneId: 'SCN-G01-01',
    trigger: 'state:S6',
    dialogueIds: ['DLG-G01-01-009'],
    requiredFirstPlay: true,
  },
  {
    sequenceId: 'SEQ-G01-01-RECOVERY',
    sceneId: 'SCN-G01-01',
    trigger: 'puzzle:PZL-G01-01-CIRCUIT',
    dialogueIds: ['DLG-G01-01-010'],
    requiredFirstPlay: true,
  },
  {
    sequenceId: 'SEQ-G01-01-FIRST-CONVERSATION',
    sceneId: 'SCN-G01-01',
    trigger: 'profile:qima:introduced',
    dialogueIds: [
      'DLG-G01-01-011',
      'DLG-G01-01-012',
      'DLG-G01-01-013',
      'DLG-G01-01-014',
      'DLG-G01-01-015',
    ],
    requiredFirstPlay: true,
  },
]
