import type { ChapterDefinition } from '../game/types'

export const G01_SCENE_01: ChapterDefinition = {
  id: 'G01',
  title: '拾光号：坠落之前',
  sceneTitle: 'SCN-G01-01 · 找回七码',
  protagonist: '星宇',
  initialState: 'S0',
  states: {
    S0: {
      id: 'S0',
      title: '失联回波',
      objective: '在导航核心舱找到失联的七码',
      narrative: '微弱回波来自右侧服务座。屏幕没有亮起。',
      safeCheckpoint: true,
    },
    S1: {
      id: 'S1',
      title: '核心检修',
      objective: '打开核心特写，找出四件修复部件',
      narrative: '七码外壳受损，核心接口仍可修复。',
    },
    S2: {
      id: 'S2',
      title: '清理接口',
      objective: '把清洁刷拖到积碳接口',
      narrative: '积碳会阻断核心识别，必须先清理。',
      safeCheckpoint: true,
    },
    S3: {
      id: 'S3',
      title: '安装芯片',
      objective: '把逻辑芯片装入左侧芯片槽',
      narrative: '接口已清理，核心槽可以重新识别芯片。',
    },
    S4: {
      id: 'S4',
      title: '接回线路',
      objective: '把接线片装到右侧接触轨',
      narrative: '核心芯片已固定，接下来恢复信号线路。',
    },
    S5: {
      id: 'S5',
      title: '恢复保护',
      objective: '把微型保险丝装入下方保护座',
      narrative: '线路已接回，最后补上核心保护元件。',
      safeCheckpoint: true,
    },
    S6: {
      id: 'S6',
      title: '启动校准',
      objective: '按冷白、琥珀、青蓝、红色的顺序校准启动线路',
      narrative: 'EDU-0077进入启动状态，等待最后的线路校准。',
      safeCheckpoint: true,
    },
  },
  items: [
    {
      id: 'ITM-G01-101',
      name: '逻辑芯片',
      description: '七码核心使用的旧式逻辑芯片。',
      inventoryIcon: '/assets/items/g01-scene-01/ITM-G01-101-chip.png',
      collectibleLayer: {
        source: '/assets/items/g01-scene-01/ITM-G01-101-chip.png',
        scope: 'zoom',
        area: { x: 12, y: 19, width: 13, height: 10 },
        rotation: -8,
      },
    },
    {
      id: 'ITM-G01-102',
      name: '接线片',
      description: '带两根短线尾的核心接线片。',
      inventoryIcon: '/assets/items/g01-scene-01/ITM-G01-102-connector.png',
      collectibleLayer: {
        source: '/assets/items/g01-scene-01/ITM-G01-102-connector.png',
        scope: 'zoom',
        area: { x: 67, y: 18, width: 11, height: 12 },
        rotation: 16,
      },
    },
    {
      id: 'ITM-G01-103',
      name: '微型保险丝',
      description: '保护七码启动回路的陶瓷保险丝。',
      inventoryIcon: '/assets/items/g01-scene-01/ITM-G01-103-micro-fuse.png',
      collectibleLayer: {
        source: '/assets/items/g01-scene-01/ITM-G01-103-micro-fuse.png',
        scope: 'zoom',
        area: { x: 44, y: 72, width: 10, height: 5 },
        rotation: -11,
      },
    },
    {
      id: 'ITM-G01-104',
      name: '清洁刷',
      description: '用于清理接口积碳的防静电硬刷。',
      inventoryIcon: '/assets/items/g01-scene-01/ITM-G01-104-cleaning-brush.png',
      collectibleLayer: {
        source: '/assets/items/g01-scene-01/ITM-G01-104-cleaning-brush.png',
        scope: 'zoom',
        area: { x: 75, y: 58, width: 13, height: 10 },
        rotation: -24,
      },
    },
  ],
  hotspots: [
    {
      id: 'HS-G01-0101',
      kind: 'inspect',
      ariaLabel: '检查右侧服务座中的七码',
      area: { x: 72, y: 27, width: 17, height: 45 },
      activeStates: ['S0'],
      scope: 'scene',
    },
    {
      id: 'HS-G01-0102',
      kind: 'zoom',
      ariaLabel: '打开七码核心检修特写',
      area: { x: 43, y: 29, width: 19, height: 38 },
      activeStates: ['S1', 'S2', 'S3', 'S4', 'S5', 'S6'],
      zoomId: 'HOS-G01-101',
      scope: 'scene',
    },
    {
      id: 'HOS-G01-101-01',
      kind: 'hidden-item',
      ariaLabel: '核心特写中的逻辑芯片',
      area: { x: 12, y: 19, width: 13, height: 10 },
      activeStates: ['S1'],
      itemId: 'ITM-G01-101',
      scope: 'zoom',
    },
    {
      id: 'HOS-G01-101-02',
      kind: 'hidden-item',
      ariaLabel: '核心特写中的接线片',
      area: { x: 67, y: 18, width: 11, height: 12 },
      activeStates: ['S1'],
      itemId: 'ITM-G01-102',
      scope: 'zoom',
    },
    {
      id: 'HOS-G01-101-03',
      kind: 'hidden-item',
      ariaLabel: '核心特写中的微型保险丝',
      area: { x: 44, y: 72, width: 10, height: 5 },
      activeStates: ['S1'],
      itemId: 'ITM-G01-103',
      scope: 'zoom',
    },
    {
      id: 'HOS-G01-101-04',
      kind: 'hidden-item',
      ariaLabel: '核心特写中的清洁刷',
      area: { x: 75, y: 58, width: 13, height: 10 },
      activeStates: ['S1'],
      itemId: 'ITM-G01-104',
      scope: 'zoom',
    },
    {
      id: 'HS-G01-0103',
      kind: 'use-target',
      ariaLabel: '积碳的核心接口',
      area: { x: 38, y: 33, width: 18, height: 25 },
      activeStates: ['S2'],
      requiredItemId: 'ITM-G01-104',
      scope: 'zoom',
    },
    {
      id: 'HS-G01-0104',
      kind: 'use-target',
      ariaLabel: '空置逻辑芯片槽',
      area: { x: 20, y: 36, width: 15, height: 23 },
      activeStates: ['S3'],
      requiredItemId: 'ITM-G01-101',
      scope: 'zoom',
    },
    {
      id: 'HS-G01-0105',
      kind: 'use-target',
      ariaLabel: '核心接线轨',
      area: { x: 59, y: 29, width: 19, height: 27 },
      activeStates: ['S4'],
      requiredItemId: 'ITM-G01-102',
      scope: 'zoom',
    },
    {
      id: 'HS-G01-0106',
      kind: 'use-target',
      ariaLabel: '微型保险丝保护座',
      area: { x: 47, y: 61, width: 12, height: 18 },
      activeStates: ['S5'],
      requiredItemId: 'ITM-G01-103',
      scope: 'zoom',
    },
  ],
  transitions: [
    { from: 'S0', event: 'inspect:HS-G01-0101', to: 'S1' },
    { from: 'S1', event: 'found:all', to: 'S2' },
    { from: 'S2', event: 'use:ITM-G01-104:HS-G01-0103', to: 'S3' },
    { from: 'S3', event: 'use:ITM-G01-101:HS-G01-0104', to: 'S4' },
    { from: 'S4', event: 'use:ITM-G01-102:HS-G01-0105', to: 'S5' },
    { from: 'S5', event: 'use:ITM-G01-103:HS-G01-0106', to: 'S6' },
    { from: 'S6', event: 'puzzle:PZL-G01-01-CIRCUIT', to: 'S6' },
  ],
}

export const G01_SCENE_01_ART = '/assets/g01-scene-01/navigation-core.png'
export const G01_SCENE_01_CORE_ART = '/assets/g01-scene-01/qima-core-closeup.png'

