import type { SceneDefinition } from '../../game/types'

const asset = (path: string) => `/assets/g02/slice-01/scn01/${path}`
const itemAsset = (path: string) => `/assets/g02/slice-01/items/${path}`

export const G02_SCN01: SceneDefinition = {
  id: 'SCN-G02-01',
  title: '旧屏幕谷外场',
  playerTitle: '五尾清算',
  art: asset('SCENE-G02-002_five-tail-rescue.webp'),
  initialState: 'S0',
  states: {
    S0: {
      id: 'S0',
      title: '吊臂落物区',
      objective: '观察阿铆上方的吊臂与安全落点',
      narrative: '五条旧吊臂在风里互相碰撞。阿铆被挂索吊在半空，清算线路仍在收紧。',
      safeCheckpoint: true,
    },
    S1: {
      id: 'S1',
      title: '救援挂索',
      objective: '把背包里的磁力挂索拖到阿铆的挂索点',
      narrative: '挂索可以把重量转移到旁边的旧框架；它不是尚未取得的磁力手套。',
    },
    S2: {
      id: 'S2',
      title: '稳定受力',
      objective: '确认挂索受力，让阿铆落到安全平台',
      narrative: '磁力挂索已经咬住支架，绷紧的清算线开始卸力。',
    },
    S3: {
      id: 'S3',
      title: '阿铆获救',
      objective: '扫描场景中的三类资源归属标签',
      narrative: '阿铆回到地面。私人、公共供暖和废弃资源标签在旧箱体间留下不同连接痕迹。',
      safeCheckpoint: true,
    },
    S4: {
      id: 'S4',
      title: '资源标签',
      objective: '继续扫描，收集三类归属证据',
      narrative: '每次真实扫描只增加一项证据；对白和软失败不会替玩家完成调查。',
    },
    S5: {
      id: 'S5',
      title: '归属推理',
      objective: '按用途和连接数量完成三类资源归属判断',
      narrative: '三类标签已收齐。把供暖连接、私人标记和废弃划痕对应起来。',
    },
    S6: {
      id: 'S6',
      title: '救援记录',
      objective: '前往旧电视墙查找借用规则档案',
      narrative: 'AUTO-G02-002 保存了阿铆救援和三类资源证据。',
      safeCheckpoint: true,
    },
  },
  items: [
    {
      id: 'RUNTIME-ITM-G02-MAGNETIC-GRAPNEL',
      name: '磁力挂索',
      description: '旧屏幕谷救援任务物；绑定 HS-G02-0003，不是磁力手套。',
      inventoryIcon: itemAsset('RUNTIME-ITM-G02-MAGNETIC-GRAPNEL_inventory.png'),
    },
  ],
  hotspots: [
    {
      id: 'RUNTIME-HS-G02-01-OBSERVE',
      kind: 'inspect',
      ariaLabel: '观察阿铆上方摇晃的吊臂和地面安全平台',
      area: { x: 32, y: 10, width: 38, height: 53 },
      activeStates: ['S0'],
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-01-DANGER',
      kind: 'inspect',
      ariaLabel: '在吊臂松脱警告期间冒险靠近阿铆',
      area: { x: 70, y: 4, width: 24, height: 34 },
      activeStates: ['S1', 'S2'],
      scope: 'scene',
    },
    {
      id: 'HS-G02-0003',
      kind: 'use-target',
      ariaLabel: '把磁力挂索拖到阿铆头顶的正式挂索点',
      area: { x: 49, y: 18, width: 13, height: 24 },
      activeStates: ['S1'],
      requiredItemId: 'RUNTIME-ITM-G02-MAGNETIC-GRAPNEL',
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-01-RESCUE-CONFIRM',
      kind: 'inspect',
      ariaLabel: '确认挂索受力并让阿铆落到安全平台',
      area: { x: 41, y: 52, width: 24, height: 30 },
      activeStates: ['S2'],
      scope: 'scene',
    },
    {
      id: 'HS-G02-0004',
      kind: 'inspect',
      ariaLabel: '检查需要未来磁力手套才能移动的钢板掩体',
      area: { x: 7, y: 52, width: 22, height: 31 },
      activeStates: ['S3', 'S4', 'S5'],
      scope: 'scene',
    },
    {
      id: 'HS-G02-0005',
      kind: 'inspect',
      ariaLabel: '扫描右下方私人资源箱的双环标签',
      area: { x: 72, y: 63, width: 14, height: 21 },
      activeStates: ['S3', 'S4'],
      scope: 'scene',
    },
    {
      id: 'HS-G02-0006',
      kind: 'inspect',
      ariaLabel: '扫描左下方公共供暖箱的三路连接标签',
      area: { x: 16, y: 67, width: 15, height: 19 },
      activeStates: ['S3', 'S4'],
      scope: 'scene',
    },
    {
      id: 'HS-G02-0007',
      kind: 'inspect',
      ariaLabel: '扫描中部废弃箱的断裂划痕标签',
      area: { x: 55, y: 69, width: 13, height: 17 },
      activeStates: ['S3', 'S4'],
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-01-CLASSIFY',
      kind: 'zoom',
      ariaLabel: '打开资源归属证据近景并完成分类',
      area: { x: 34, y: 55, width: 24, height: 26 },
      activeStates: ['S5'],
      zoomId: 'RUNTIME-PUZ-G02-RESOURCE-CLASSIFICATION',
      scope: 'scene',
    },
  ],
  transitions: [
    { from: 'S0', event: 'inspect:RUNTIME-HS-G02-01-OBSERVE', to: 'S1' },
    { from: 'S1', event: 'inspect:RUNTIME-HS-G02-01-DANGER', to: 'S1' },
    { from: 'S2', event: 'inspect:RUNTIME-HS-G02-01-DANGER', to: 'S2' },
    {
      from: 'S1',
      event: 'use:RUNTIME-ITM-G02-MAGNETIC-GRAPNEL:HS-G02-0003',
      to: 'S2',
    },
    { from: 'S2', event: 'inspect:RUNTIME-HS-G02-01-RESCUE-CONFIRM', to: 'S3' },
    { from: 'S3', event: 'inspect:HS-G02-0005', to: 'S4' },
    { from: 'S3', event: 'inspect:HS-G02-0006', to: 'S4' },
    { from: 'S3', event: 'inspect:HS-G02-0007', to: 'S4' },
    { from: 'S4', event: 'inspect:HS-G02-0005', to: 'S4' },
    { from: 'S4', event: 'inspect:HS-G02-0006', to: 'S4' },
    { from: 'S4', event: 'inspect:HS-G02-0007', to: 'S4' },
    { from: 'S3', event: 'inspect:HS-G02-0004', to: 'S3' },
    { from: 'S4', event: 'inspect:HS-G02-0004', to: 'S4' },
    { from: 'S5', event: 'inspect:HS-G02-0004', to: 'S5' },
    {
      from: 'S5',
      event: 'puzzle:RUNTIME-PUZ-G02-RESOURCE-CLASSIFICATION',
      to: 'S6',
    },
  ],
}
