import type { ItemDefinition, SceneDefinition } from '../../game/types'

const asset = (path: string) => `/assets/g02/slice-01/scn02/${path}`
const itemAsset = (path: string) => `/assets/g02/slice-01/items/${path}`

const item = (
  id: string,
  name: string,
  description: string,
  area: { x: number; y: number; width: number; height: number },
  rotation: number,
): ItemDefinition => ({
  id,
  name,
  description,
  inventoryIcon: itemAsset(`${id}_inventory.png`),
  collectibleLayer: {
    source: itemAsset(`${id}_scene.png`),
    scope: 'zoom',
    area,
    rotation,
  },
})

export const G02_SCN02: SceneDefinition = {
  id: 'SCN-G02-02',
  title: '旧电视墙',
  playerTitle: '谁说这是无主之物',
  art: asset('SCENE-G02-003_tv-wall-archive.webp'),
  initialState: 'S0',
  states: {
    S0: {
      id: 'S0',
      title: '沉默的电视墙',
      objective: '调查三块熄灭的主屏和下方碎片堆',
      narrative: '旧电视墙被拆得只剩三块主屏。借用记录停在一次未完成的归还上。',
      safeCheckpoint: true,
    },
    S1: {
      id: 'S1',
      title: '屏幕碎片堆',
      objective: '在真实近景中找齐三枚电源键、两段短线和镜面屏片',
      narrative: '目标物混在断线、键帽和碎螺丝之间；拾取后会从场景层真实消失。',
    },
    S2: {
      id: 'S2',
      title: '修复准备',
      objective: '根据磨损边缘，把正确电源键和短线装到主屏 A',
      narrative: '六件目标已进入背包。镜面屏片反射着远处四组能量信号，先留在背包里。',
      safeCheckpoint: true,
    },
    S3: {
      id: 'S3',
      title: '主屏 A 点亮',
      objective: '按接口数量修复主屏 B',
      narrative: '第一块屏幕显示“6 路借用记录”，第二块屏幕缺少四接点短线。',
    },
    S4: {
      id: 'S4',
      title: '主屏 B 点亮',
      objective: '用剩余电源键恢复主屏 C',
      narrative: '第二块屏幕恢复“4 路归还记录”。第三块的污迹不是数字，而是磨损方向。',
    },
    S5: {
      id: 'S5',
      title: '借用档案',
      objective: '读取三屏合并后的借、用、还档案',
      narrative: '三块主屏已经点亮，档案可以被真实读取，但尚未归档。',
    },
    S6: {
      id: 'S6',
      title: '档案恢复',
      objective: '带着恢复的档案回到旧屏幕谷安全区',
      narrative: '借用档案、三屏修复状态与随身物品都已自动保存。四组能量信号等待路线确认。',
      safeCheckpoint: true,
    },
  },
  items: [
    item('ITM-G02-002', '电源键 A', '边缘有六个浅色接点。', { x: 10, y: 19, width: 9, height: 13 }, -14),
    item('ITM-G02-003', '电源键 B', '背面磨损与四接点短线相合。', { x: 69, y: 18, width: 8, height: 12 }, 21),
    item('ITM-G02-004', '电源键 C', '右下角有一道斜向缺口。', { x: 42, y: 56, width: 8, height: 12 }, -31),
    item('RUNTIME-ITM-G02-005-A', '短线 A', '铜芯完整的六接点短线。', { x: 22, y: 65, width: 13, height: 9 }, 38),
    item('RUNTIME-ITM-G02-005-B', '短线 B', '护套磨旧的四接点短线。', { x: 78, y: 57, width: 12, height: 9 }, -23),
    item('ITM-G02-006', '镜面屏片', '镜面涂层仍完整，能反射远处微弱的能量信号。', { x: 50, y: 18, width: 11, height: 15 }, 12),
  ],
  hotspots: [
    {
      id: 'HS-G02-0011',
      kind: 'inspect',
      ariaLabel: '调查电视墙下方塞满旧零件的屏幕碎片堆',
      area: { x: 29, y: 54, width: 44, height: 35 },
      activeStates: ['S0'],
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-02-HOS-ZOOM',
      kind: 'zoom',
      ariaLabel: '打开屏幕碎片堆找物近景',
      area: { x: 28, y: 55, width: 46, height: 34 },
      activeStates: ['S1'],
      zoomId: 'HOS-G02-001',
      scope: 'scene',
    },
    {
      id: 'HOS-G02-001-A',
      kind: 'hidden-item',
      ariaLabel: '在左上旧遥控器后找到电源键 A',
      area: { x: 10, y: 19, width: 9, height: 13 },
      activeStates: ['S1'],
      itemId: 'ITM-G02-002',
      scope: 'zoom',
      hosId: 'HOS-G02-001',
    },
    {
      id: 'HOS-G02-001-B',
      kind: 'hidden-item',
      ariaLabel: '在右上网兜边找到电源键 B',
      area: { x: 69, y: 18, width: 8, height: 12 },
      activeStates: ['S1'],
      itemId: 'ITM-G02-003',
      scope: 'zoom',
      hosId: 'HOS-G02-001',
    },
    {
      id: 'HOS-G02-001-C',
      kind: 'hidden-item',
      ariaLabel: '在中央断线下找到电源键 C',
      area: { x: 42, y: 56, width: 8, height: 12 },
      activeStates: ['S1'],
      itemId: 'ITM-G02-004',
      scope: 'zoom',
      hosId: 'HOS-G02-001',
    },
    {
      id: 'HOS-G02-001-LINE-A',
      kind: 'hidden-item',
      ariaLabel: '在左下旧标签后找到短线 A',
      area: { x: 22, y: 65, width: 13, height: 9 },
      activeStates: ['S1'],
      itemId: 'RUNTIME-ITM-G02-005-A',
      scope: 'zoom',
      hosId: 'HOS-G02-001',
    },
    {
      id: 'HOS-G02-001-LINE-B',
      kind: 'hidden-item',
      ariaLabel: '在右下螺丝堆边找到短线 B',
      area: { x: 78, y: 57, width: 12, height: 9 },
      activeStates: ['S1'],
      itemId: 'RUNTIME-ITM-G02-005-B',
      scope: 'zoom',
      hosId: 'HOS-G02-001',
    },
    {
      id: 'HOS-G02-001-MIRROR',
      kind: 'hidden-item',
      ariaLabel: '在中央旧屏壳后找到镜面屏片',
      area: { x: 50, y: 18, width: 11, height: 15 },
      activeStates: ['S1'],
      itemId: 'ITM-G02-006',
      scope: 'zoom',
      hosId: 'HOS-G02-001',
    },
    {
      id: 'RUNTIME-HS-G02-0008-KEY',
      kind: 'use-target',
      ariaLabel: '把正确电源键拖入主屏 A 的六接点键槽',
      area: { x: 14, y: 22, width: 18, height: 29 },
      activeStates: ['S2'],
      requiredItemId: 'ITM-G02-002',
      scope: 'scene',
    },
    {
      id: 'HS-G02-0008',
      kind: 'use-target',
      ariaLabel: '把六接点短线拖入主屏 A',
      area: { x: 14, y: 48, width: 18, height: 14 },
      activeStates: ['S2'],
      requiredItemId: 'RUNTIME-ITM-G02-005-A',
      requiredCompletedHotspotIds: ['RUNTIME-HS-G02-0008-KEY'],
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-0009-KEY',
      kind: 'use-target',
      ariaLabel: '把正确电源键拖入主屏 B 的四接点键槽',
      area: { x: 41, y: 22, width: 18, height: 29 },
      activeStates: ['S3'],
      requiredItemId: 'ITM-G02-003',
      scope: 'scene',
    },
    {
      id: 'HS-G02-0009',
      kind: 'use-target',
      ariaLabel: '把四接点短线拖入主屏 B',
      area: { x: 41, y: 48, width: 18, height: 14 },
      activeStates: ['S3'],
      requiredItemId: 'RUNTIME-ITM-G02-005-B',
      requiredCompletedHotspotIds: ['RUNTIME-HS-G02-0009-KEY'],
      scope: 'scene',
    },
    {
      id: 'HS-G02-0010',
      kind: 'use-target',
      ariaLabel: '根据斜向磨损把正确电源键拖入主屏 C',
      area: { x: 68, y: 22, width: 18, height: 40 },
      activeStates: ['S4'],
      requiredItemId: 'ITM-G02-004',
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-02-ARCHIVE',
      kind: 'inspect',
      ariaLabel: '读取三块主屏拼合出的借用规则档案',
      area: { x: 31, y: 20, width: 39, height: 42 },
      activeStates: ['S5'],
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-02-DANGER',
      kind: 'inspect',
      ariaLabel: '触碰电视墙后方仍在放电的裸露电缆',
      area: { x: 88, y: 22, width: 10, height: 43 },
      activeStates: ['S2', 'S3', 'S4'],
      scope: 'scene',
    },
  ],
  transitions: [
    { from: 'S0', event: 'inspect:HS-G02-0011', to: 'S1' },
    { from: 'S1', event: 'found:all', to: 'S2' },
    { from: 'S2', event: 'use:ITM-G02-002:RUNTIME-HS-G02-0008-KEY', to: 'S2' },
    {
      from: 'S2',
      event: 'use:RUNTIME-ITM-G02-005-A:HS-G02-0008',
      to: 'S3',
    },
    { from: 'S3', event: 'use:ITM-G02-003:RUNTIME-HS-G02-0009-KEY', to: 'S3' },
    {
      from: 'S3',
      event: 'use:RUNTIME-ITM-G02-005-B:HS-G02-0009',
      to: 'S4',
    },
    { from: 'S4', event: 'use:ITM-G02-004:HS-G02-0010', to: 'S5' },
    { from: 'S5', event: 'inspect:RUNTIME-HS-G02-02-ARCHIVE', to: 'S6' },
    { from: 'S2', event: 'inspect:RUNTIME-HS-G02-02-DANGER', to: 'S2' },
    { from: 'S3', event: 'inspect:RUNTIME-HS-G02-02-DANGER', to: 'S3' },
    { from: 'S4', event: 'inspect:RUNTIME-HS-G02-02-DANGER', to: 'S4' },
  ],
}
