import type { SceneDefinition } from '../../game/types'

const asset = (path: string) => `/assets/g02/slice-01/scn00/${path}`

export const G02_SCN00: SceneDefinition = {
  id: 'SCN-G02-00',
  title: '旧屏幕谷外缘',
  playerTitle: '垃圾雨之前',
  art: asset('SCENE-G02-001_old-screen-valley-pulse.webp'),
  initialState: 'S0',
  states: {
    S0: {
      id: 'S0',
      title: '谷口落点',
      objective: '观察落点附近可以挡住碎片的结构',
      narrative: '垃圾雨擦过旧屏幕谷外缘，蓝色封存脉冲在碎片之间短促闪烁。',
      safeCheckpoint: true,
    },
    S1: {
      id: 'S1',
      title: '断卫星轴',
      objective: '靠近断卫星轴，确认掩体后的扫描角度',
      narrative: '断裂的卫星轴形成一段低矮掩体。碎片风经过时，背风侧仍保持稳定。',
    },
    S2: {
      id: 'S2',
      title: '封存脉冲',
      objective: '打开局部扫描近景，匹配七码的取样节拍',
      narrative: '蓝光每隔固定间距重复一次。只有在稳定间隔内完成扫描，记录才有效。',
    },
    S3: {
      id: 'S3',
      title: '扫描样本',
      objective: '核对脉冲样本中重复出现的封存标记',
      narrative: '七码完成了真实扫描。样本中没有求救码，只有管理员封存信号。',
    },
    S4: {
      id: 'S4',
      title: '样本复核',
      objective: '让七码复核封存来源',
      narrative: '运行时适配状态用于补全正式状态表缺失的复核步骤，不改变正式数据。',
    },
    S5: {
      id: 'S5',
      title: '扫描归档',
      objective: '确认自动存档并收起扫描近景',
      narrative: '封存脉冲证据已经归档，落点信息保存在 AUTO-G02-001。',
      safeCheckpoint: true,
    },
    S6: {
      id: 'S6',
      title: '进入旧屏幕谷',
      objective: '沿掩体进入旧屏幕谷外场',
      narrative: '碎片风短暂减弱。前方传来吊臂松脱和金属索绷紧的声音。',
      safeCheckpoint: true,
    },
  },
  items: [],
  hotspots: [
    {
      id: 'HS-G02-0001',
      kind: 'inspect',
      ariaLabel: '调查画面左侧斜插在碎片中的断卫星轴',
      area: { x: 8, y: 36, width: 28, height: 42 },
      activeStates: ['S0'],
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-00-DANGER',
      kind: 'inspect',
      ariaLabel: '观察掩体外正在掠过的磁性碎片风',
      area: { x: 63, y: 5, width: 28, height: 28 },
      activeStates: ['S1', 'S2', 'S3', 'S4'],
      scope: 'scene',
    },
    {
      id: 'HS-G02-0002',
      kind: 'inspect',
      ariaLabel: '在断卫星轴后锁定蓝色封存脉冲的真实位置',
      area: { x: 43, y: 27, width: 20, height: 28 },
      activeStates: ['S1'],
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-00-PULSE-ZOOM',
      kind: 'zoom',
      ariaLabel: '打开七码封存脉冲扫描近景',
      area: { x: 39, y: 24, width: 28, height: 34 },
      activeStates: ['S2'],
      zoomId: 'RUNTIME-PUZ-G02-PULSE-SCAN',
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-00-SAMPLE',
      kind: 'inspect',
      ariaLabel: '核对脉冲扫描样本中的重复封存标记',
      area: { x: 39, y: 49, width: 25, height: 24 },
      activeStates: ['S3'],
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-00-VERIFY',
      kind: 'inspect',
      ariaLabel: '让七码复核封存脉冲来源并归档证据',
      area: { x: 64, y: 54, width: 18, height: 25 },
      activeStates: ['S4'],
      scope: 'scene',
    },
    {
      id: 'RUNTIME-HS-G02-00-EXIT',
      kind: 'inspect',
      ariaLabel: '确认扫描自动存档并沿掩体进入旧屏幕谷',
      area: { x: 83, y: 28, width: 15, height: 52 },
      activeStates: ['S5'],
      scope: 'scene',
    },
  ],
  transitions: [
    { from: 'S0', event: 'inspect:HS-G02-0001', to: 'S1' },
    { from: 'S1', event: 'inspect:HS-G02-0002', to: 'S2' },
    { from: 'S2', event: 'puzzle:RUNTIME-PUZ-G02-PULSE-SCAN', to: 'S3' },
    { from: 'S3', event: 'inspect:RUNTIME-HS-G02-00-SAMPLE', to: 'S4' },
    { from: 'S4', event: 'inspect:RUNTIME-HS-G02-00-VERIFY', to: 'S5' },
    { from: 'S5', event: 'inspect:RUNTIME-HS-G02-00-EXIT', to: 'S6' },
  ],
}
